language: node_js
node_js:
  - 10.19.0
cache: npm
install:
  - npm install
script:
  - npm run test
  - npm run build
env:
  global:
    secure: Ltila4eKXhgBIbJvt9MdsBj4TIyljoXGzlI6iLzSwVNgiWa0hjuW/z2/XPgFOU4zPXP++sdRRiRjtABfHNycrO2ThhEJurwLko+D53JWXwiOkdHGlmkHGPoaz45vQNfOzqnQdn+FUkYB0QABErCOXI2WED1/xQyLcrDCXEYFm6saGh8kNOMHcMxIzhG9Tn9VfH3NhwxmoQTT/DePzaPuZF45+G271VvPdWECbxpSpq5nIfvdQQMCOOHpH4e1qnGgaX2Mu7RO0OEAYi1qeZ0IgR6/M7NvdoTEkORmyDUH/cJqO5UOsVSOO4zPqwerfLqfzgbtuHQSIDFi4hoaho0ksJZnp/p9ljeaSdUoqMGWxTY5/OZosQdMf6MosvfC3RlJ0lzSRw8Ajt4IbvyNjJgZuDvsZNf0iETfPoX+KwGF7/cHqPacT0a3Nz0zxkkoQWeVoplXZKACoxpQP3yCXKSEPpgjWIaXpvAR+z2BJgzaSRoDCkpOF0GUDjtA/CCA3FlSimZwl1756s3mMUdDsi0GZvcGRCIcghDeAwCqxB1otk+uFyGaujoNy9QzkgTr8OcvU4+T0BSXh8pD9sCuhrmaVea6dpDlra6fNIE0tyXM0x7KZb47XXbT0jfREcvZvYzpqrDAFn9Hf2HXBB0FWDS8rjARTujZpqHokS2uxBJcMxA=
deploy:
  provider: firebase
  token:
    secure: Ltila4eKXhgBIbJvt9MdsBj4TIyljoXGzlI6iLzSwVNgiWa0hjuW/z2/XPgFOU4zPXP++sdRRiRjtABfHNycrO2ThhEJurwLko+D53JWXwiOkdHGlmkHGPoaz45vQNfOzqnQdn+FUkYB0QABErCOXI2WED1/xQyLcrDCXEYFm6saGh8kNOMHcMxIzhG9Tn9VfH3NhwxmoQTT/DePzaPuZF45+G271VvPdWECbxpSpq5nIfvdQQMCOOHpH4e1qnGgaX2Mu7RO0OEAYi1qeZ0IgR6/M7NvdoTEkORmyDUH/cJqO5UOsVSOO4zPqwerfLqfzgbtuHQSIDFi4hoaho0ksJZnp/p9ljeaSdUoqMGWxTY5/OZosQdMf6MosvfC3RlJ0lzSRw8Ajt4IbvyNjJgZuDvsZNf0iETfPoX+KwGF7/cHqPacT0a3Nz0zxkkoQWeVoplXZKACoxpQP3yCXKSEPpgjWIaXpvAR+z2BJgzaSRoDCkpOF0GUDjtA/CCA3FlSimZwl1756s3mMUdDsi0GZvcGRCIcghDeAwCqxB1otk+uFyGaujoNy9QzkgTr8OcvU4+T0BSXh8pD9sCuhrmaVea6dpDlra6fNIE0tyXM0x7KZb47XXbT0jfREcvZvYzpqrDAFn9Hf2HXBB0FWDS8rjARTujZpqHokS2uxBJcMxA=
  branch: master
